Repository Ryuji-Facilities/Coding-challenge, pull requests merged in 2022-10, with the labels that each got.

#2 add sub Directories
  CONTRIBUTING.md
  Learning-Resources.md
  README.md
Labels: hacktoberfest-accepted

#3 add dummy Files
  Go/main.go
  Python/main.py
  Rust/main.rs
Labels: enhancement

#4 [PYTHON] - Add Bubble Sort Algorithm
  CONTRIBUTING.md
  Python/bubbleSort.py
Labels: hacktoberfest-accepted

#5 [GO] - Add password generator
  Go/passGen/main.go
Labels: enhancement

#7 [GO] - Add Linear Search algorithm
  Go/linearSearch/main.go
Labels: hacktoberfest

#9 [PYTHON] - Add "Summarizes long text paragraphs"
  Python/Text_summarization.py
Labels: hacktoberfest

#10 [RUST] - Add Bubble Sort algorithm
  Rust/Sparkle/BubbleSort.rs
Labels: hacktoberfest

#11 [RUST] - Add Quick Sort algorithm
  Rust/Quik/QuicSort.rs
Labels: hacktoberfest

#12 Create password-generator.py
  Python/password-generator.py
Labels: hacktoberfest

#13 [RUST] - Add Merge Sort algorithm
  Rust/Merged/MergeSort.rs
Labels: hacktoberfest

#14 [TYPESCRIPT] - OOP Implementation in Typescript
  Typescript/oopImplement.ts
Labels: hacktoberfest

#15 [TYPESCRIPT] - Selection Sort in TS
  Typescript/selectionSort.ts
Labels: hacktoberfest

#16 [TYPESCRIPT] - Add Merge Sort algo
  Typescript/mergeSort.ts
Labels: hacktoberfest

#6 Create hacktoberfest.py
  Python/hacktoberfest.py
Labels: hacktoberfest-accepted, hacktoberfest

#17 [PYTHON] - Create Binary Search
  Python/Binary Search.py
Labels: hacktoberfest

#18 [GO] - Add counting sort algorithm
  Go/countingSort/main.go
Labels: hacktoberfest

#19 [GO] - add Selection Sort Algorithm
  Go/selectionSort/main.go
Labels: hacktoberfest

#21 [GO] - add Merge Sort algorithm
  Go/mergeSort/main.go
Labels: hacktoberfest

#22 Syncing
  CONTRIBUTING.md
  Go/countingSort/main.go
  Go/dir.go
  Go/linearSearch/main.go
  Go/main.go
  Go/mergeSort/main.go
  Go/selectionSort/main.go
  PHP/dir.php
  Python/Binary Search.py
  Python/Text_summarization.py
  Python/dir.py
  Python/hacktoberfest.py
  Python/main.py
  Python/password-generator.py
  README.md
  Rust/Merged/MergeSort.rs
  Rust/PasswordGen/main.rs
  Rust/Quik/QuicSort.rs
  Rust/Sparkle/BubbleSort.rs
  Rust/dir.rs
  Rust/main.rs
  Typescript/dir.ts
  Typescript/mergeSort.ts
  Typescript/oopImplement.ts
  Typescript/selectionSort.ts
Labels: hacktoberfest
